Add lithuanian language
computernewb/collab-vm-1.2-webapp pull request #112
Opened 2024-11-19 10:23 UTC by thany2010

2024-11-19 11:31 UTC, mvoolt commented
Your GitHub profile says you are from Thailand, Are you sure this is not a machine translation?

2024-11-19 12:12 UTC, thany2010 commented
> Your GitHub profile says you are from Thailand, Are you sure this is not a machine translation?

Yes

2024-11-19 12:32 UTC, mvoolt commented
> > Your GitHub profile says you are from Thailand, Are you sure this is not a machine translation?
> 
> Yes

How did you learn Lithuanian?

2024-11-26 18:20 UTC, TruncatedDinoSour requested changes
There's a lot of issues with literal translation, wrong language, and ignoring of context. Feels like many parts of this document were translated using either an automated translator (script?) or an LLM model such as ChatGPT. I've left comments in Lithuanian suggesting what things to change in the JSON translation, but I believe you should in general go through most translations and verify whether or not they fit in the context <3

Good luck!

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kWelcomeModal_Body": "<p>Prieš tęsdami susipažinkite su mūsų taisyklėmis:</p> <h3>R1. Nepažeisk įstatymų.</h3> Nenaudokite CollabVM ar CollabVM tinklo, kad pažeistumėte Jungtinių Valstijų federali
Dalys skamba neformaliai ir kartais nelabai teisingai mano nuomone. Manau, jog galėtum pakeisti frazes bei naudoti labiau pasyvę kalbą. Pavyzdžiui:

> Jei „CollabVM“ aptiks, jog per jos paslaugą buvo įvykdytas nusikaltimas, būsite nedelsiant užblokuoti (O gal geriau būtų "jūsų preiga bus uždrausta"/tt), o prireikus, apie jūsų veiklą gali būti pranešta valdžios institucijoms.

Ši dalis:

> Įstatymai įpareigoja „CollabVM“ pranešti teisėsaugos institucijoms, jei tai taps žinote, kad jos tinkle yra vaikų pornografijos arba ji perduodama

Skamba jog ji buvo išversta vertėjo, kadangi panaudota netaisyklinga "žinote" forma.

Taip pat kaip ir "Nenaudokite „CollabVM“ DoS / DDoS asmeniui, verslui, įmonei ar bet kam kitam." kur yra nepilnai taisyklingai sudarytas teiginys/taisyklė. Geriau būtų pasakyti "Nenaudokite „CollabVM“ tinklų DoS / DDoS atakomis asmenims, verslams / įmonėms ar bet kam kitam." ar pan.

Dalys kaip "Nepiktnaudžiaukite jokiais išnaudojimais, be to, jei matote, kad kažkas piktnaudžiauja išnaudojimais arba jums reikia apie tai pranešti, susisiekite su manimi: computernewbab@gmail.com" galėtų panaudoti internacionalinę arba bent jau taisyklingesnę kalbą geresniam supratimui ką turi omeny. Pvz "Nepiktnaudžiaukite jokiais pažeidžiamumais, be to, jei matote, kad kažkas piktnaudžiauja jais arba jus norite apie tai pranešti, susisiekite su CollabVM komanda: computernewbab@gmail.com" ar kažkas tokio.

Be to, R1, R2, R3, ... galėtų irgi būti išversta į T1, T2, T3 (rule => taisyklė) nu bet čia pedantikos.

Manau galėtum pertvarkyti visą vertimą, kadangi šioje stadijoje vertimas atrodo labai netvarkingas.

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kSiteButtons_Languages": "Kalbos",
Šviesusis*

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kVM_TurnTimeTimer": "Posūkis baigiasi po {0} sek.",
Versta tiesiogai, "turn" šiame kontekste yra susietas su eilės tvarka ir CollabVM ėjimų struktūra,

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kVM_WaitingTurnTimer": "Laukiama posūkio po {0} sek.",
Tas parts tiesioginis vertimias.

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kVMButtons_TakeTurn": "Pasukite",
Tiesioginis "turn" vertimas - pagalvokite su kontekstu "take a turn to control a virtual machine" :)

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kVMButtons_VoteForReset": "Balsuokite už atstatymą",
Neteisinga forma, turi būti "balsuoti" CollabVM UI kontekste,

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kAdminVMButtons_IndefiniteTurn": "Neribotas posūkis",
Neteisingos formos bei tiesioginiai vertimai kurie nepaiso konteksto. Pataisykite :)

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kAdminVMButtons_GhostTurnOff": "Vaiduoklių išjungimas (išjungtas)",
Skamba keistai. Nieka negirdėjau apie šią CollabVM funkciją, bet vėlgi skamba tiesiogiai versta vertėjo arba ChatGPT(?)

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kAdminVMButtons_Kick": "Spyris",
Gal "ban" bei "kick" geriau būtų palinkti internacionaline kalba (baninti, kickinti ar pan.), arba bent jau pataisyti tiek formą tiek implikacijas.

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kAdminVMButtons_GetIP": "Gaukite IP",
Neteisingos gramatinės formos kontekste.

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kError_UnexpectedDisconnection": "Jūs buvote atjungtas nuo serverio.",
Gal būtų visai neblogai panauti pasyvę formą?

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kAccountModal_Verify": "Patvirtinti el",
Turėjote omeny "el. paštą" gal?

2024-11-26 18:20 UTC, ar1ja commented on static/lang/lt-lt.json
> +		"kAccountModal_VerifyPasswordResetText": "Išsiuntėme el. laišką adresu {0}. Norėdami iš naujo nustatyti slaptažodį, įveskite 8 skaitmenų kodą iš toliau pateikto el. pašto.",
Kaip suprasti "toliau", gal turit omeny "anksčiau"?

2024-11-26 18:22 UTC, TruncatedDinoSour commented on static/lang/lt-lt.json
> +		"kVM_WaitingTurnTimer": "Laukiama posūkio po {0} sek.",
Pats * sorry typo lol

2026-07-15 05:57 UTC, closed without merging

2026-07-15 05:57 UTC, elijahr2411 commented
closing since the issues brought up by @ar1ja were never addressed.